site_name: Django Ninja
site_description: Django Ninja - Django REST framework with high performance, easy to learn, fast to code.
site_url: https://django-ninja.rest-framework.com
repo_name: vitalik/django-ninja
repo_url: https://github.com/vitalik/django-ninja
edit_uri: ""
extra:
  analytics:
    provider: google
    property: UA-170474207-1
extra_css:
  - extra.css
theme:
  name: material
  palette:
    primary: green
  logo: img/docs-logo.png
  favicon: img/favicon.png
  language: en
  icon:
    repo: fontawesome/brands/github-alt
nav:
  - Intro: index.md
  - motivation.md
  - Tutorial:
      - "First Steps": tutorial/index.md
      - "Parsing Input": tutorial/step2.md
      - "Handling Responses": tutorial/step3.md
      - Other Tutorials:
          - tutorial/other/video.md
          - tutorial/other/crud.md
  - How-to Guides:
      - Parsing input:
          - guides/input/operations.md
          - guides/input/path-params.md
          - guides/input/query-params.md
          - guides/input/body.md
          - guides/input/form-params.md
          - guides/input/file-params.md
          - guides/input/request-parsers.md
      - Handling responses:
          - Defining a Schema: guides/response/index.md
          - guides/response/temporal_response.md
          - Generating a Schema from Django models: guides/response/django-pydantic.md
          - Generating a Schema dynamically: guides/response/django-pydantic-create-schema.md
          - guides/response/config-pydantic.md
          - guides/response/pagination.md
          - guides/response/response-renderers.md
      - Splitting your API with Routers: guides/routers.md
      - guides/authentication.md
      - guides/api-docs.md
      - guides/errors.md
      - guides/urls.md
      - guides/async-support.md
      - guides/versioning.md
  - Reference:
      - NinjaAPI class: reference/api.md
      - reference/csrf.md
      - reference/operations-parameters.md
      - reference/management-commands.md
      - reference/settings.md
      - releases.md
  - help.md
  - Enhancement Proposals:
      - Intro: proposals/index.md
      - proposals/cbv.md
      - proposals/v1.md
markdown_extensions:
  - markdown_include.include
  - markdown.extensions.codehilite:
      guess_lang: false
  # Uncomment these 2 lines during development to more easily add highlights
  #- pymdownx.highlight:
  #    linenums: true
  - abbr
  - codehilite
  - admonition
  - pymdownx.superfences
plugins:
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - from django.conf import settings
            - settings.configure()
      watch:
        - ../ninja
