name: Full Test

on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
        django-version: ['<3.0', '<3.1', '<3.2', '<3.3', '<4.1', '<4.2', '<4.3']
        exclude:
          - python-version: '3.12'
            django-version: '<3.0'
          - python-version: '3.12'
            django-version: '<3.1'
          - python-version: '3.12'
            django-version: '<3.2'
          - python-version: '3.12'
            django-version: '<3.3'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install core
        run: pip install "Django${{ matrix.django-version }}" "pydantic<3"
      - name: Install tests
        run: pip install pytest pytest-asyncio pytest-django psycopg2-binary
      - name: Test
        run: pytest

  coverage:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Flit
        run: pip install flit
      - name: Install Dependencies
        run: flit install --symlink
      - name: Test
        run: pytest --cov=ninja

  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Flit
        run: pip install flit
      - name: Install Dependencies
        run: flit install --symlink
      - name: Black
        run: black --check ninja tests
      - name: Ruff
        run: ruff ninja tests
      - name: mypy
        run: mypy ninja tests/mypy_test.py
